// Level to Title Mapping
const levelTitles: Record<number, string> = {
    10: "Novice Adventurer",
    20: "Aspiring Explorer",
    30: "Seasoned Fighter",
    40: "Elite Warrior",
    50: "Master Tactician",
    60: "Hero of the Land",
    70: "Demon Slayer",
    80: "Guardian of Justice",
    90: "Legendary Champion",
    100: "Immortal Knight",
    110: "Dragon Conqueror",
    120: "Celestial Hero",
    130: "Shadow Reaper",
    140: "Blade Master",
    150: "Arcane Lord",
    160: "Titan Slayer",
    170: "Divine Avenger",
    180: "Eternal Gladiator",
    190: "Supreme Commander",
    200: "God of War",
    210: "Mythical Guardian",
    220: "The Phantom Lord",
    230: "Doombringer",
    240: "Void Walker",
    250: "Stormbringer",
    260: "Master of Fate",
    270: "Infinity Seeker",
    280: "Overlord of Chaos",
    290: "Paragon of Light",
    300: "Ascended One",
    310: "The Unbreakable",
    320: "The Forsaken King",
    330: "Nightmare Incarnate",
    340: "Ruler of Dimensions",
    350: "Primordial Sage",
    360: "Celestial General",
    370: "Hellfire Monarch",
    380: "Duskbringer",
    390: "Immortal Guardian",
    400: "Lord of the Abyss",
    410: "Ancient Titan",
    420: "The Dark Prophet",
    430: "Stormborn Tyrant",
    440: "Aether Warden",
    450: "The Invincible",
    460: "The Deathless One",
    470: "Eclipse Sovereign",
    480: "Soulbinder",
    490: "Master of Eternity",
    500: "The One Above All",
    510: "The Infernal King",
    520: "The Archmage Supreme",
    530: "The Omniscient",
    540: "The Astral Wanderer",
    550: "Abyssal Lord",
    560: "The Alpha and Omega",
    570: "Ragnarok Bringer",
    580: "Harbinger of Doom",
    590: "Eldritch Overlord",
    600: "Cosmic Vanquisher",
    610: "Titanborn Monarch",
    620: "The Endbringer",
    630: "Sovereign of Fate",
    640: "Divine Paragon",
    650: "Champion of Legends",
    660: "Celestial Juggernaut",
    670: "Godslayer",
    680: "Ethereal Emperor",
    690: "Primordial Overlord",
    700: "The Eternal One",
    710: "Master of All",
    720: "Omnipotent Ruler",
    730: "Chaos Incarnate",
    740: "The Supreme Deity",
    750: "Invoker of the End",
    760: "The Transcendent",
    770: "The Boundless",
    780: "Sage of Infinite Wisdom",
    790: "Dreadlord of Shadows",
    800: "The Timeless One",
    810: "Eternal Flame Wielder",
    820: "Master of the Cosmos",
    830: "Invoker of the Stars",
    840: "Reaper of Worlds",
    850: "The Reality Shaper",
    860: "The Titanborn Sage",
    870: "Omniversal King",
    880: "The Boundless Lord",
    890: "Apex Warlord",
    900: "Avatar of Infinity",
    910: "The Supreme Conqueror",
    920: "Sovereign of the Realms",
    930: "The All-Knowing One",
    940: "The Divine Judge",
    950: "Monarch of Creation",
    960: "The Cosmic Harbinger",
    970: "The Master Architect",
    980: "Invoker of Eternity",
    990: "The Infinite Emperor",
    1000: "The Absolute Overlord",
    1010: "God of the Unknown",
    1020: "The Time Weaver",
    1030: "Supreme Arbiter",
    1040: "The Grand Oracle",
    1050: "The Universe Guardian",
    1060: "Master of Dimensions",
    1070: "Elder God of Chaos",
    1080: "The Transcendent Warlord",
    1090: "The Divine Punisher",
    1100: "Infinity Ruler",
    1110: "The Eternal Guardian",
    1120: "The Dream Architect",
    1130: "The Celestial Shaper",
    1140: "The Infinity Seeker",
    1150: "The Titan King",
    1160: "The All-Father",
    1170: "The Celestial Tyrant",
    1180: "The Cosmic General",
    1190: "The Omniversal Guardian",
    1200: "The Supreme Creator",
    1210: "Overlord of Multiverse",
    1220: "Master of Realities",
    1230: "Architect of Fate",
    1240: "The Boundless Warrior",
    1250: "King of Infinite Wars",
    1260: "Master of All Beings",
    1270: "The Grand Emperor",
    1280: "The Timeless Monarch",
    1290: "Supreme Warbringer",
    1300: "Omnipresent Guardian",
    1310: "Sage of All Time",
    1320: "Reality Shatterer",
    1330: "Ultimate Existence",
    1340: "The Infinite Titan",
    1350: "The Grand Overlord",
    1360: "Final Arbiter",
    1370: "Celestial Titan",
    1380: "Eternal Ascendant",
    1390: "God of Everything",
    1400: "The Omniversal God",
    1500: "Supreme Existence",
    1600: "Beyond the Gods",
    1700: "The Ultimate Monarch",
    1800: "Ruler of All Creation",
    1900: "The Supreme Architect",
    2000: "The One Above All"
  };
  
  // Function to get title based on level
  export const getTitleForLevel = (level: number): string => {
    const sortedLevels = Object.keys(levelTitles)
      .map(Number)
      .sort((a, b) => a - b);
  
    let currentTitle = "Nameless Warrior"; // Default Title
  
    for (const lvl of sortedLevels) {
      if (level >= lvl) {
        currentTitle = levelTitles[lvl];
      } else {
        break;
      }
    }
  
    return currentTitle;
  };
  